apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: fleetman-queue

  ports:
    - name: http
      port: 8161
      nodePort: 30030

    - name: endpoint
      port: 61616

  type: NodePort
