apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker

spec:
  #Defining which pods are going to be represented by this Service
  #The service becomes a network endpoint for other services or external users
  selector:
    app: position-tracker

  ports:
    - name: http
      port: 8080

  type: ClusterIP

