apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  #Defining which pods are going to be represented by this Service
  #The service becomes a network endpoint for other services or external users
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort

